// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAijKAPe20zU3DhA7PpXJeMhZ966nPuVG0',
    appId: '1:89503389618:web:9330bb6e1853d17b64b6ab',
    messagingSenderId: '89503389618',
    projectId: 'authenticationflutter-caf6d',
    authDomain: 'authenticationflutter-caf6d.firebaseapp.com',
    storageBucket: 'authenticationflutter-caf6d.appspot.com',
    measurementId: 'G-6TB57R6859',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOXrf90-7kkUXGA5Umwsq-e8mBYIqaLuQ',
    appId: '1:89503389618:android:e45c936aa760070964b6ab',
    messagingSenderId: '89503389618',
    projectId: 'authenticationflutter-caf6d',
    storageBucket: 'authenticationflutter-caf6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq6IBGwSjRQgzfzJ4JQwAZfQ9LyUb2-GE',
    appId: '1:89503389618:ios:f5fc4f6e4bdf6bd964b6ab',
    messagingSenderId: '89503389618',
    projectId: 'authenticationflutter-caf6d',
    storageBucket: 'authenticationflutter-caf6d.appspot.com',
    iosClientId: '89503389618-conbjhdo20biid5dihmhqpgitmq7l1ot.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentiactionex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq6IBGwSjRQgzfzJ4JQwAZfQ9LyUb2-GE',
    appId: '1:89503389618:ios:f5fc4f6e4bdf6bd964b6ab',
    messagingSenderId: '89503389618',
    projectId: 'authenticationflutter-caf6d',
    storageBucket: 'authenticationflutter-caf6d.appspot.com',
    iosClientId: '89503389618-conbjhdo20biid5dihmhqpgitmq7l1ot.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentiactionex',
  );
}
